stages:
  - prebuild
  - test
  - build
  - deploy

prebuild:
  stage: prebuild
  script:
    - touch .npmignore
    - npm install -g gatsby
    - npm install

test:
  stage: test
  script: npm test

build:
  stage: build
  script: npm build

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  only:
  - development

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod-zds.zepdev.net
  only:
  - master
