# pull in node 10 docker image
image: node:10.15.0

stages:
  - test
  - quality
  - build
  - deploy

.cache_template: &cache_definition
  # put node_modules and .cache to cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

# test stage, run unit tests
test:
  before_script:
    - yarn
  <<: *cache_definition
  script:
    - yarn test
  stage: test

# sonar qube code quality job
sonarqube_master_job:
  <<: *cache_definition
  stage: test
  script:
    - yarn sonar-scanner -Dsonar.login=SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.json_mode=CODECLIMATE -Dsonar.gitlab.failure_notification_mode=commit-status
  only:
    - development
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - codeclimate.json

sonarqube_preview_job:
  <<: *cache_definition
  stage: test
  script:
    - git merge $CI_COMMIT_SHA --no-commit --no-ff
    # - yarn sonar-scanner -X -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.json_mode=CODECLIMATE -Dsonar.gitlab.failure_notification_mode=commit-status
    - yarn sonar-scanner -X -Dsonar.gitlab.api_version=v3 -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  artifacts:
    expire_in: 1 day
    paths:
      - codeclimate.json

codequality:
  stage: quality
  variables:
    GIT_STRATEGY: none
  script:
    - echo ok
  artifacts:
    paths:
      - codeclimate.json

# build stage, node_modules are downloaded from cache
build:
  <<: *cache_definition
  stage: build
  script: yarn build
  # create artifacts from the public directory
  artifacts:
    paths:
      - public/

deploy_development:
  stage: deploy
  image: python:latest
  variables:
    TARGET_BUCKET_NAME: 'zds-dev'
    AWS_REGION: 'eu-central-1'
    CLOUDFRONT_DISTRIBUTION: 'ET351YZOMAVPH'
  script:
    - pip install awscli
    - aws s3 sync ./public/ s3://$TARGET_BUCKET_NAME/ --delete --exclude="*node_modules/*" --include "*"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  # use artifacts from build stage
  dependencies:
    - build
  only:
    - development

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod-zds.zepdev.net
  only:
    - master
