image: node:10.15.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/

stages:
  - test
  - build
  - deploy

test:
 before_script:
   - yarn
 stage: test
 script: yarn test

build:
  before_script:
    - yarn
  stage: build
  script: yarn build
  artifacts:
    paths:
      - public/


deploy_development:
  stage: deploy
  image: ruby:latest
  variables:
    TARGET_BUCKET_NAME: "zds-dev"
    AWS_REGION: "eu-central-1"
    CLOUDFRONT_DISTRIBUTION: "ET351YZOMAVPH"
  script:
  - gem install dpl
  - dpl --provider=s3 --bucket=$TARGET_BUCKET_NAME --region=$AWS_REGION --local-dir=public --skip_cleanup=true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths \"/*\"
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  dependencies:
    - build
  only:
  - development

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod-zds.zepdev.net
  only:
  - master
