image: node:10.15.0
image: gatsbyjs/gatsby

# before_script:
#   - touch .npmignore
#   - npm install -g yarn gatsby
#   - yarn install

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: yarn test

build:
  stage: build
  script: yarn build

deploy_development:
  stage: deploy
  script:
    - export TARGET_BUCKET_NAME=zds-dev
    - export TARGET_ADDRESS=https://dev-zds.zepdev.net
    - export AWS_REGION=eu-central-1
    - gatsby-plugin-s3 deploy --yes
    # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths \"/*\"
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  only:
  - development

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod-zds.zepdev.net
  only:
  - master
