# pull in node 10 docker image
image: node:10.15.0

stages:
  - test
  - build
  - deploy

.cache_template: &cache_definition
  # put node_modules and .cache to cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - coverage/

# test stage, run unit tests and linting
test:
  before_script:
    - yarn
  <<: *cache_definition
  script:
    - yarn format
    - yarn test
  stage: test

# sonar qube code quality job
sonarqube:
  <<: *cache_definition
  stage: test
  script:
    - yarn eslint-sonarqube
    - yarn sonar-scanner -Dsonar.login=$SONAR_LOGIN
  only:
    - development
    - master

# build stage, node_modules are downloaded from cache
build:
  <<: *cache_definition
  stage: build
  script: yarn build
  # create artifacts from the public directory
  artifacts:
    paths:
      - public/

.deploy_template:
  stage: deploy
  image: python:latest
  # scripts to be run on deployment
  script:
    - pip install awscli
    - aws s3 sync ./public/ s3://$TARGET_BUCKET_NAME/ --delete --exclude="*node_modules/*" --include "*"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
  # use artifacts from build stage
  dependencies:
    - build

deploy_development:
  extends: .deploy_template
  variables:
    TARGET_BUCKET_NAME: 'zds-dev'
    AWS_REGION: 'eu-central-1'
    CLOUDFRONT_DISTRIBUTION: 'ET351YZOMAVPH'
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  only:
    - development

deploy_production:
  extends: .deploy_template
  variables:
    TARGET_BUCKET_NAME: 'zds-live'
    AWS_REGION: 'eu-central-1'
    CLOUDFRONT_DISTRIBUTION: 'E3N62GDZMDUN0M'
  environment:
    name: production
    url: https://live-zds.zepdev.net
  # only trigger deployment into production manually
  when: manual
  only:
    - master
