image: node:10.15.0

before_script:
  - touch .npmignore
  - npm install -g yarn gatsby
  - yarn install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: yarn test

build:
  stage: build
  script: yarn build

deploy_development:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: development
    url: https://dev-zds.zepdev.net
  only:
  - development

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod-zds.zepdev.net
  only:
  - master
