version: 2.1
orbs:
  node: circleci/node@0.0.7
  aws-cli: circleci/aws-cli@0.1.2
  aws-s3: circleci/aws-s3@1.0.0
executors:
  node_10:
    docker:
      - image: circleci/node:10.15
jobs:
  test:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Prettier
          command: yarn format
      - run:
          name: Run all tests
          command: yarn test
  build:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Build public dir
          command: yarn build
  deploy:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - run: echo "deploying!!!" # run the `echo` command

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build